# Generated by Django 2.2 on 2020-01-28 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0007_auto_20200128_1232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='items',
            new_name='item',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='items',
        ),
        migrations.AddField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(blank=True, null=True, to='carts.CartItem'),
        ),
    ]
