# Generated by Django 2.2 on 2020-01-28 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0009_auto_20200128_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='ordered_items',
        ),
        migrations.AddField(
            model_name='cart',
            name='ordered_items',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carts.CartItem'),
        ),
    ]
