# Generated by Django 2.2 on 2020-01-28 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20200127_1348'),
        ('carts', '0010_auto_20200128_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='items',
        ),
        migrations.AddField(
            model_name='cart',
            name='items',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Item'),
        ),
        migrations.RemoveField(
            model_name='cart',
            name='ordered_items',
        ),
        migrations.AddField(
            model_name='cart',
            name='ordered_items',
            field=models.ManyToManyField(blank=True, null=True, to='carts.CartItem'),
        ),
    ]
