# Generated by Django 2.2 on 2020-01-29 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_variation_category'),
        ('carts', '0014_cartitem_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='Variations',
            field=models.ManyToManyField(blank=True, null=True, to='products.Variation'),
        ),
    ]
