# Generated by Django 2.2 on 2020-01-29 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0015_cartitem_variations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='Variations',
            new_name='variations',
        ),
    ]
