# Generated by Django 3.0.3 on 2020-02-12 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0016_auto_20200129_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='total',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='line_total',
            field=models.FloatField(default=0.0),
        ),
    ]
