# Generated by Django 3.0.3 on 2020-02-10 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_auto_20200210_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='url_link',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
