# Generated by Django 2.2 on 2020-02-05 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_emailconfirmed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailconfirmed',
            old_name='hashKey',
            new_name='activation_key',
        ),
    ]
