# Generated by Django 3.0.3 on 2020-02-11 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_userdefaultaddress'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraddress',
            options={'ordering': ['updated', '-created']},
        ),
    ]
