# Generated by Django 3.0.3 on 2020-02-12 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200211_1547'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraddress',
            old_name='town',
            new_name='city',
        ),
    ]
