# Generated by Django 3.0.3 on 2020-02-12 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200212_1328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraddress',
            old_name='city',
            new_name='town',
        ),
    ]
