# Generated by Django 3.0.3 on 2020-02-12 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200203_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='final_total',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='order',
            name='sub_total',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='order',
            name='tax_total',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated',
            field=models.DateTimeField(),
        ),
    ]
