# Generated by Django 3.0.3 on 2020-02-12 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200211_1547'),
        ('orders', '0005_auto_20200212_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='billing_address',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='billing_address', to='accounts.UserAddress'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='shipping_address', to='accounts.UserAddress'),
        ),
    ]
